python -c "from test0 import test_prime;test_prime(2,True)"
python -c "from test0 import test_prime;test_prime(3,True)"
python -c "from test0 import test_prime;test_prime(10,False)"
python -c "from test0 import test_prime;test_prime(25,False)"
python -c "from test0 import test_prime;test_prime(17,True)"
python -c "from test0 import test_prime;test_prime(1,True)"
